### PR TITLE
use the new container infrastructure in travis

### PR DESCRIPTION
**Pull request by stevejhiggs**

### CODE REVIEW

**Comment by andyroyle** [comment]
let me check the docs on using the container-based infra with sauce

**Comment by matteofigus** [comment]
We test with [container infrastructure with travis and sauce](https://travis-ci.org/opentable/oc), and works - may be something else?

**Comment by andyroyle** [comment]
@matteofigus yeah, turns out to be the version of protractor thats causing the (current) issue. Will upgrade and see what else shakes loose

**Comment by stevejhiggs** [comment]
Unfortunately the only way to test all of this stuff is In a live pull request

**Comment by andyroyle** [comment]
:hankey:

**Comment by stevejhiggs** [comment]
I'm going to recreate this pull request without all the messing around

**Pull request closed without merging**
