### PR TITLE
[Thoughts/Needs Testing] Refactoring to support different persistence layer

### PR DESCRIPTION
**Pull request by tombuildsstuff**
As discussed in #165 - making it possible to switch out the persistence layer in Hobknob

Rather than calling etcd directly - I'm proxying it in a layer. The reason for this is two-fold:
 1) we'd like to put an API on top of the persistence layer, and have clients connect to that - rather than directly to the persistence layer
 2) it makes it possible to support a different backend, like for instance Consul or Postgres - or even the API mentioned above

From our side - we've been talking about using Consul to potentially store this - so I'd suggest we continue the discussion within #165. Either way this PR would allow multiple persistence layers if we wanted to go that way.

This, obviously needs some proper testing if we do decide to take it further - but seems fine for me running locally. I should _probably_ check the e2e tests too..

Some minor stuff too:
 - Add a `failure flash` when Azure gives you Auth problems
 - Made the LB Path configurable (as ours is stored elsewhere)

Thoughts @andyroyle @matteofigus @ryantomlinson @chriscartlidge etc?

### CODE REVIEW

**Comment by stevejhiggs** [comment]
some linting fails, oddly tests still seem to pass despite everything bombing out....hmmm

**Comment by tombuildsstuff** [comment]
@stevejhiggs my bad - fixed

**Comment by stevejhiggs** [comment]
lgtm, wouldn't mind one other persons feedback though

**Comment by andyroyle** [comment]
makes sense to me, allows us to have a range of "officially" supported backends.

**Comment by tombuildsstuff** [comment]
@matteofigus ish - the implementation hasn't drastically changed - but the config file has. There's 2 x new params - dataSource / loadBalancerFile

**Comment by matteofigus** [comment]
In that case, I would say that we could 1) Make it not a breaking change by setting defaults in such way that this can be a safe 2.X upgrade 2) Make it a breaking change and start bringing it to a 3.X branch?

**Comment by tombuildsstuff** [comment]
We've been talking about a 3.0 anyway, so perhaps it makes sense to be the first part of that? If everyone agrees - can someone create that branch and I'll update the PR? @matteofigus

**Comment by tombuildsstuff** [comment]
@matteofigus I've pushed an empty commit to the `3.0` branch - adding a changelog, and then updated this PR to point to that. Mind taking another look?

**Comment by chriscartlidge** [comment]
Sorry I've been away on holiday. 

@tombuildsstuff This is really good! Like you say this helps us to make everyone happy re https://github.com/opentable/hobknob/issues/165 .

The code looks good to me. I'm happy to merge... @matteofigus Want to take a quick look?

**Comment by tombuildsstuff** [comment]
🎉

I'm planning to send a follow up to refactor the imports too - providing everyone's cool with that? That'll take it from `require('../../../foo')` to `require(__base + '/foo')` - which makes refactoring a ton simpler going forward (the work's done - just based on this branch)

**Comment by matteofigus** [comment]
LGTM but I would keep the __base refactoring to a different PR. Specifically, I have things against it but I think it would be off-topic to discuss about that in this thread 🌴

**Pull request merged**
